# Generated by Django 3.2.5 on 2021-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
