# Generated by Django 3.2.5 on 2021-07-25 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telescopes', '0002_telescope_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
